import { AlertTriangle } from "lucide-react";

const RiskDisclaimer = () => {
  return (
    <section className="relative z-10 py-12 px-4 bg-[#111315] border-t-0 border-b border-[#C8935A]/10">
      <div className="container mx-auto max-w-4xl">
        <div className="flex flex-col md:flex-row gap-4 items-start">
          <div className="flex-shrink-0 mt-0.5">
            <AlertTriangle className="h-6 w-6 text-[#C8935A]" aria-hidden />
          </div>
          <div className="space-y-3">
            <h2 className="sr-only">Risk &amp; Regulatory Disclosure</h2>
            <h3 className="text-lg font-semibold text-[#E2B485]">
              Risk Disclaimer
            </h3>
            <div className="space-y-3 text-sm text-[#9CA3AF] leading-relaxed">
              <p>
                <strong className="text-[#E0E0E0]">Capital at risk.</strong>{" "}
                Trading Forex, gold, and leveraged instruments can result in
                losses that exceed your initial deposit. Past signal performance
                does not guarantee future results.
              </p>
              <p>
                <strong className="text-[#E0E0E0]">Not financial advice.</strong>{" "}
                PipFactor is an analytical tool. Signals are generated by AI
                models trained on market data and news sentiment. They are not
                personalised financial advice, and PipFactor is not a licensed
                financial advisor or regulated broker.
              </p>
              <p>
                All trading decisions are solely your responsibility. Only trade
                capital you can afford to lose. Consider your risk tolerance and
                consult a qualified financial adviser if needed.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default RiskDisclaimer;
